MIKLATS = [
 {
  "name":"Botique HaGiva",
  "address":"HaAvoda Street 1",
  "lat":32.07881561,
  "long":34.84879607,
  "size":100.0,
  "type":"Public",
  "description":null,
  "isPublic":true,
  "comments":null,
  "cityID":503.0,
  "addressHeb":"העבודה 1",
  "nameHeb":"בוטיק הגבעה",
  "commentsHeb":null
 },
 {
  "name":"Shufersal",
  "address":"David Ben Gurion Street 18",
  "lat":32.07728844,
  "long":34.84674331,
  "size":150.0,
  "type":"Public",
  "description":null,
  "isPublic":true,
  "comments":null,
  "cityID":514.0,
  "addressHeb":"בן גוריון 18",
  "nameHeb":"שופרסל",
  "commentsHeb":null
 },
 {
  "name":"Gan Golani",
  "address":"Herzl Street 4",
  "lat":32.07506268,
  "long":34.84931257,
  "size":150.0,
  "type":"Public",
  "description":null,
  "isPublic":true,
  "comments":null,
  "cityID":511.0,
  "addressHeb":"הרצל 4",
  "nameHeb":"גן גולני",
  "commentsHeb":null
 },
 {
  "name":"Yad LBanim",
  "address":"Sderot HaGiborim",
  "lat":32.0760697,
  "long":34.8486997,
  "size":70.0,
  "type":"Public",
  "description":null,
  "isPublic":true,
  "comments":null,
  "cityID":510.0,
  "addressHeb":"שדרות הגבורים",
  "nameHeb":"יד לבנים",
  "commentsHeb":null
 },
 {
  "name":"Kidum Noar",
  "address":"Be'eri St & Ha-Zeitim St",
  "lat":32.07987355,
  "long":34.85221805,
  "size":100.0,
  "type":"Public",
  "description":null,
  "isPublic":true,
  "comments":null,
  "cityID":507.0,
  "addressHeb":"הזיתים פינת בארי",
  "nameHeb":"קידום נוער",
  "commentsHeb":null
 },
 {
  "name":"Mercaz Hatachlut",
  "address":"HaNasi Street 18",
  "lat":32.08074242,
  "long":34.8516817,
  "size":120.0,
  "type":"Public",
  "description":null,
  "isPublic":true,
  "comments":null,
  "cityID":505.0,
  "addressHeb":"הנשיא 18",
  "nameHeb":"מרכז התחלות",
  "commentsHeb":null
 },
 {
  "name":"French Synagogue",
  "address":"HaNasi Street 17",
  "lat":32.08102392,
  "long":34.85126022,
  "size":120.0,
  "type":"Public",
  "description":null,
  "isPublic":true,
  "comments":null,
  "cityID":506.0,
  "addressHeb":"הנשיא 17",
  "nameHeb":"בי\"כ צרפתים",
  "commentsHeb":null
 },
 {
  "name":"Beit El Synagogue",
  "address":"HaNasi Street 13-14",
  "lat":32.081032,
  "long":34.849944,
  "size":100.0,
  "type":"Public",
  "description":null,
  "isPublic":true,
  "comments":null,
  "cityID":504.0,
  "addressHeb":"הנשיא 13-14",
  "nameHeb":"בית אל",
  "commentsHeb":null
 },
 {
  "name":"Beit Midrash",
  "address":"HaNasi Street 9-12",
  "lat":32.081341,
  "long":34.849216,
  "size":100.0,
  "type":"Public",
  "description":null,
  "isPublic":true,
  "comments":null,
  "cityID":509.0,
  "addressHeb":"הנשיא 9-12",
  "nameHeb":"בית מדרש",
  "commentsHeb":null
 },
 {
  "name":"Midrash Shmuel",
  "address":"HaNasi Street 5-8",
  "lat":32.081649,
  "long":34.848609,
  "size":128.0,
  "type":"Public",
  "description":null,
  "isPublic":true,
  "comments":null,
  "cityID":501.0,
  "addressHeb":"הנשיא 5-8",
  "nameHeb":"מדרש שמואל",
  "commentsHeb":null
 },
 {
  "name":"Community Center Branch",
  "address":"HaNasi Street 1-4",
  "lat":32.082125,
  "long":34.847213,
  "size":100.0,
  "type":"Public",
  "description":null,
  "isPublic":true,
  "comments":null,
  "cityID":508.0,
  "addressHeb":"הנשיא 1-4",
  "nameHeb":"שלוחת המתנ\"ס",
  "commentsHeb":null
 },
 {
  "name":"Bialik Street 3",
  "address":"Bialik Street 3",
  "lat":32.07835,
  "long":34.846239,
  "size":null,
  "type":"Apartment",
  "description":"in basement",
  "isPublic":false,
  "comments":null,
  "cityID":null,
  "addressHeb":"ביאליק 3",
  "nameHeb":"ביאליק 3",
  "commentsHeb":null
 },
 {
  "name":"Alonim St 4a",
  "address":"Alonim St 4a",
  "lat":32.069192,
  "long":34.846499,
  "size":null,
  "type":"Apartment",
  "description":"in basement",
  "isPublic":false,
  "comments":null,
  "cityID":null,
  "addressHeb":"אלונים 4א",
  "nameHeb":"אלונים 4א",
  "commentsHeb":null
 },
 {
  "name":"David Elazar Street 10",
  "address":"David Elazar Street 10",
  "lat":32.0796,
  "long":34.847398,
  "size":null,
  "type":"Apartment",
  "description":"on ground floor",
  "isPublic":false,
  "comments":null,
  "cityID":null,
  "addressHeb":"דוד אלעזר 10",
  "nameHeb":"דוד אלעזר 10",
  "commentsHeb":null
 },
 {
  "name":"Rahvat Ilan 12a",
  "address":"Rahvat Ilan 12a",
  "lat":32.070864,
  "long":34.846486,
  "size":null,
  "type":"Apartment",
  "description":"in basement",
  "isPublic":false,
  "comments":null,
  "cityID":null,
  "addressHeb":"רחבת אילן 12א",
  "nameHeb":"רחבת אילן 12א",
  "commentsHeb":null
 },
 {
  "name":"Yoni Netanyahu St 20",
  "address":"Yoni Netanyahu St 20",
  "lat":32.075378,
  "long":34.855317,
  "size":null,
  "type":"Apartment",
  "description":"in stairwell",
  "isPublic":false,
  "comments":null,
  "cityID":null,
  "addressHeb":"יוני נתניהו 20",
  "nameHeb":"יוני נתניהו 20",
  "commentsHeb":null
 },
 {
  "name":"David Ben Gurion Street 5",
  "address":"David Ben Gurion Street 5",
  "lat":32.07734,
  "long":34.846587,
  "size":null,
  "type":"Apartment",
  "description":"on ground floor",
  "isPublic":false,
  "comments":null,
  "cityID":null,
  "addressHeb":"בן גוריון 5",
  "nameHeb":"בן גוריון 5",
  "commentsHeb":null
 }
]